// tailwind.config.js
module.exports = {
  content: ['./*', './*'],
  theme: {
    extend: {
      colors: {
        primary: '#5c67f7',
        'primary-hover': '#5C67F7E6',
        primary1: '#e354d4',
        'primary1-hover': '#f170e2f6',
        primary2: '#ff5d9f',
        'primary2-hover': '#fc6da6',
        primary3: '#ff8e6f',
        'primary3-hover': '#f9997e',
        secondary: '#9e5cf7',
        'secondary-hover': '#9E5CF7E6',
        success: '#21ce9e',
        'success-hover': '#21CE9EE6',
        danger: '#fb4242',
        'danger-hover': '#FB4242E6',
        warning: '#ffc658',
        'warning-hover': '#FFC658E6',
        info: '#0ea5e8',
        'info-hover': '#FFC658E6',
        purple: '#A86CF8',
        'purple-hover': '#898efe',
        teal: '#20dece',
        'teal-hover': '#32ecdc',
        orange: '#fe7c58',
        'orange-hover': '#fe8361',
        light: '#f9f9fa',
        'light-hover': '#f9f9fad8',
        dark: '#0a0a0a',
        'dark-hover': '#0a0a0ae6',
      },
    },
  },
  plugins: [],
};
